In [1]:
from mobilechelonian import turtle

ModuleNotFoundError: No module named 'mobilechelonian'

In [3]:
!pip install mobilechelonian

In [4]:
from mobilechelonian import turtle

ImportError: cannot import name 'turtle' from 'mobilechelonian' (/Users/AbrahamJC/anaconda3/lib/python3.7/site-packages/mobilechelonian/__init__.py)

In [6]:
from mobilechelonian import Turtle

In [7]:
t = Turtle()
t.speed(5)
colours=["red","blue","yellow","brown","black","purple","green"]
t.penup(); t.left(90); t.forward(200); t.right(90); t.pendown()
for i in range (0,18):
    t.pencolor(colours[i%7])
    t.right(20)
    t.forward(50)
t.right(180)
t.home()

Turtle()

In [24]:
t = Turtle()
t.speed(1)
colours=["red","blue","yellow","brown","black","purple","green"]
t.penup(); t.left(90); t.forward(200); t.right(90); t.pendown()
for i in range (0,5):
    t.pencolor(colours[i%7])
    t.right(45)
    t.forward(90)
t.right(90)
t.home()

Turtle()

In [26]:
t = Turtle()
t.speed(5)
colours=["red","blue","yellow","brown","black","purple","green"]
t.penup(); t.left(90); t.forward(200); t.right(90); t.pendown()
for i in range (0,5):
    t.pencolor(colours[i%7])
    t.right(45)
    t.forward(90)
t.right(60)
t.home()

Turtle()

In [27]:
t = Turtle()
t.speed(1)
colours=["red","blue","yellow","brown","black","purple","green"]
t.penup(); t.left(90); t.forward(200); t.right(90); t.pendown()
for i in range (0,5):
    t.pencolor(colours[i%7])
    t.right(45)
    t.forward(90)
t.right(90)
t.home()

Turtle()

In [31]:
t = Turtle()
t.speed(10)
colours=["red","blue","yellow","brown","black","purple","green"]
t.penup(); t.left(90); t.forward(100); t.right(90); t.pendown()
for i in range (0,5):
    t.pencolor(colours[i%9])
    t.right(90)
    t.forward(90)
t.right(90)
t.home()

Turtle()

In [32]:
a = [1,2,3,4]
b = [2,4,6,8]

In [55]:
import numpy as np


In [57]:
x = np.array([2,1,3])
y = np.array([4,6,7])
print(x+y)
#print(type(x))

[ 6  7 10]


In [58]:
x*y

array([ 8,  6, 21])

In [59]:
sum(x*y)

35

In [60]:
np.dot(x,y)

35

In [61]:
x@y

35

In [63]:
np.linalg.norm(x)

3.7416573867739413

In [65]:
A = np.array([[1,2,3],[4,5,6],[7,8,9]])
B = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])
print(A)
print(B)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [66]:
A+B

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [67]:
A-B

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [68]:
A*B

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])

In [69]:
A@B

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])

In [70]:
A.shape

(3, 3)

In [71]:
A.size

9

In [73]:
print(np.arange(1,10,.1))

[1.  1.1 1.2 1.3 1.4 1.5 1.6 1.7 1.8 1.9 2.  2.1 2.2 2.3 2.4 2.5 2.6 2.7
 2.8 2.9 3.  3.1 3.2 3.3 3.4 3.5 3.6 3.7 3.8 3.9 4.  4.1 4.2 4.3 4.4 4.5
 4.6 4.7 4.8 4.9 5.  5.1 5.2 5.3 5.4 5.5 5.6 5.7 5.8 5.9 6.  6.1 6.2 6.3
 6.4 6.5 6.6 6.7 6.8 6.9 7.  7.1 7.2 7.3 7.4 7.5 7.6 7.7 7.8 7.9 8.  8.1
 8.2 8.3 8.4 8.5 8.6 8.7 8.8 8.9 9.  9.1 9.2 9.3 9.4 9.5 9.6 9.7 9.8 9.9]


In [74]:
print(np.arange(1,10).reshape(3,3))

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [75]:
np.linalg.det(A)

-9.51619735392994e-16